---
- name: Including users file
  include_vars:
    file: files/users.yml

- name: Creating groups
  group: name="{{item.name}}" gid="{{item.gid | default(omit)}}"
  with_items: "{{groups_to_create}}"
  tags: ['users','groups','configuration']

- name: Add groups to sudo
  lineinfile:
      path: /etc/sudoers
      insertafter: EOF
      line: "%{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
  when: "item.sudo_group == True"
  with_items: "{{groups_to_create}}"

- name: Per-user group creation
  group: name="{{item.username}}"
         gid="{{item.gid | default(item.uid) | default(omit)}}"
  with_items: "{{users}}"
  when: "'group' not in item and users_create_per_user_group"
  tags: ['users','configuration']

- name: User creation
  user:
    name: "{{item.username}}"
    group: "{{item.group | default(item.username if users_create_per_user_group else users_group)}}"
    groups: "{{item.groups | join(',') if 'groups' in item else ''}}"
    shell: "{{item.shell if item.shell is defined else users_default_shell}}"
    password: "{{item.password if item.password is defined else '!'}}"
    comment: "{{item.name if item.name is defined else ''}}"
    uid: "{{item.uid | default(omit)}}"
    home: "/home/{{ item.username }}"
    createhome: "{{'yes' if users_create_homedirs else 'no'}}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    update_password: "{{item.update_password | default(omit)}}"
  with_items: "{{users}}"
  when: "item.username in users_to_create or users_to_create.0 == 'all'"
  tags: ['users','configuration']

- name: SSH keys
  authorized_key:
    user: "{{item.0.username}}"
    key: "{{item.1}}"
    path: "{{ item.0.home | default('/home/' + item.0.username) }}/.ssh/authorized_keys"
  with_subelements:
    - "{{users}}"
    - ssh_key
    - skip_missing: yes
  when: "item.0.username in users_to_create"
  tags: ['users','configuration']

- name: Setup user profiles
  blockinfile:
    block: "{{item.profile}}"
    dest: "{{ item.home | default('/home/' + item.username) }}/.profile"
    owner: "{{item.username}}"
    group: "{{item.group | default(item.username if users_create_per_user_group else users_group)}}"
    mode: 0644
    create: true
  with_items: "{{users}}"
  when: "(users_create_homedirs and item.profile is defined) and item.username in users_to_create"

- name: Change ssh policy to ssh keys only
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    replace: 'PasswordAuthentication no'
  register: sshd_config
  when: ssh_nopass

- name: Restart ssh service
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed 

- name: Deleted user removal
  user:
    name: "{{item.username}}"
    state: absent
    remove: "{{item.remove | default(omit)}}"
    force: "{{item.force | default(omit)}}"
  with_items: "{{users_deleted | default([])}}"
  tags: ['users','configuration']

- name: Deleted users homedir removal
  file:
      state: absent
      path: "/home/{{ item.username }}"
  with_items: "{{users_deleted | default([])}}"
  when: "item.delete_homedir is defined and item.delete_homedir == True"

- name: Deleted per-user group removal
  group: name="{{item.username}}" state=absent
  with_items: "{{users_deleted | default([])}}"
  when: users_create_per_user_group
